# Generated by Django 3.0.3 on 2020-12-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
    ]
